Image module ready
kikiondo/ToDo pull request #3
Opened 2018-10-27 01:47 UTC by kikiondo

This branch has one feature.

Show and add the image

2018-10-29 04:34 UTC, diegosaul402 requested changes
In general, looks good but have some issues to address in order to merge

2018-10-29 04:34 UTC, diegosaul402 commented on Gemfile
> +# shrine
if you won't use this gem there is no need commit it

2018-10-29 04:34 UTC, diegosaul402 commented on Gemfile
> +gem 'pry'
pry should be only on deb and test environments

2018-10-29 04:34 UTC, diegosaul402 commented on app/controllers/users/confirmations_controller.rb
> +  # GET /resource/confirmation/new
You shouldn't commit commented code, better delete it or finish the implementation before ask for revision

2018-11-02 00:28 UTC, diegosaul402 requested changes
Attend this and previous comments before continue

2018-11-02 00:28 UTC, diegosaul402 commented on Gemfile
> +gem 'pry'
Maybe I didn't explain correctly, you should move the `pry` gem to the test and development environments, and remove `byebug`, its not required if you're using pry

2018-11-02 00:28 UTC, diegosaul402 commented on app/controllers/application_controller.rb
> +   devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :image])
You're still using variable names in Spanish, change them.

2018-11-09 23:56 UTC, archisss approved these changes

2018-11-10 00:33 UTC, AlejandroHdzM commented
LGTM

2018-11-10 00:35 UTC, AlejandroHdzM approved these changes
LGTM

2018-11-10 00:36 UTC, merged